// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftebgyioixhpbjwzqkzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0ZWJneWlvaXhocGJqd3pxa3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjQ5MzUsImV4cCI6MjA2NTU0MDkzNX0.7PcinM018zwIGf3VaMHa5sSK9elcIcO3NYHfATFCAX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);